# TODO: This image should be refactored out into a new repo or something
# It's Dockerfile is in the Serverless repo
default:
  image: passthesecret/ci-build-environment:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - python3 -m pip install -r requirements.txt
  - python3 -m unittest discover -s tests --verbose

production:
  stage: deploy
  script:
  - python3 -m pip install twine
  - python3 setup.py sdist
  - twine upload dist/*
  only:
  - tags
