# TODO: This image should be refactored out into a new repo or something
# It's Dockerfile is in the Serverless repo
default:
  image: passthesecret/ci-build-environment:latest

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
  - pip install --upgrade pip
  - pip install poetry
  - poetry --version
  - poetry install -vv
  - poetry export --format requirements.txt --without-hashes --output requirements.txt

test:
  stage: test
  script:
  - python3 -m unittest discover -s tests --verbose

production:
  stage: deploy
  script:
  - poetry install -vv twine
  - python3 setup.py sdist
  - twine upload dist/*
  only:
  - tags
