default:
  image: passthesecret/ci-build-environment:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - python3 -m pip install -r requirements.txt
  - python3 -m unittest discover -s tests --verbose

production:
  stage: deploy
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - python3 -m pip install twine
  - python3 setup.py sdist
  - twine upload dist/*
  only:
  - master
